<?xml version="1.0"?>
<package format="2">
  <name>b2arx_description</name>
  <version>0.1.0</version>
  <description>Visual description assets for Unitree B2 + ARX R5a (b2arx) combined robot model.</description>

  <maintainer email="lxk@xiaokang.local">lxk</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>urdf</exec_depend>

  <test_depend>python3-nose</test_depend>

  <export/>
</package>
